#!/bin/sh
set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

echo "Running pre-push hook..."

cd "$REPO_ROOT"
make fmt
make lint
make check

git add .
# git commit -m "build 'binary file' for release/push bin/auto-commit"

echo "[+] Success pre-push!"
