name: Tests git-auto-commit

on:
    pull_request:
        branches: [main]

jobs:
    go_check:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Install Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.23.0'

            - name: Run tests
              run: |
                  make test